name: mersali_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+2

  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  country_list_pick: ^1.0.1+3
  country_code_picker: ^1.7.0
  im_stepper: ^0.1.2+9
  url_launcher: ^5.7.10
  intl: ^0.16.1
  flutter_datetime_picker: ^1.4.0
  date_time_picker: ^1.1.1
  carousel_pro: ^1.0.0
  email_validator: ^1.0.0
  pin_code_fields: ^6.0.2
  flare_flutter: ^2.0.6
  get: ^3.24.0
  http: ^0.12.2
  toast: ^0.1.5 


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - lib/lang/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
